### PR TITLE
feat: change fast-equals to fast-deep-equal; 1kb less

### PR DESCRIPTION
**Pull request by denisx**
Package fast-deep-equal is the most npm popular (50M) and top-fast (https://github.com/epoberezkin/fast-deep-equal)

Profit: less for 1 kB

### CODE REVIEW

**Comment by denisx** [comment]
@ckifer sorry for ping (or suggest me another maintainer)

**Comment by ckifer** [comment]
Hey @denisx 

This has been suggested before. Even though `fast-deep-equal` is the most popular it is essentially an abandoned project which we would rather not depend on

https://github.com/epoberezkin/fast-deep-equal/issues/145

**Comment by denisx** [comment]
What about [react-fast-compare](https://github.com/FormidableLabs/react-fast-compare) ? @ckifer

**Comment by ckifer** [comment]
That looks better

**Pull request closed without merging**
