### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by denisx**
Add  `"sideEffects": false` for better codspliting

### CODE REVIEW

**Comment by denisx** [comment]
@ckifer I need you help. We need to go a quick 2 minute adventure.

**Comment by ckifer** [comment]
Not sure what you mean about a 2 minute adventure. 

I'm fine with doing this, but it may not help as much as it seems it might

**Review by ckifer — APPROVED** [review]

**Comment by denisx** [comment]
When can we wait for new publich patch version?

**Comment by ckifer** [comment]
Are you saying publish in general or publish and then install in recharts? I can publish it as soon as a get a few minutes. I can't install it in recharts 2.x, only once 3.0 is out because it goes across a breaking change (3.0 to 4.0)

**Comment by denisx** [comment]
can we patch 3 and 4 versions?

**Comment by ckifer** [comment]
generally I wouldn't go back and patch 3.x no. Being that this is a small change it shouldn't be a huge deal

**Comment by denisx** [comment]
Ok, will think about 4 mirgation

**Comment by ckifer** [comment]
are using using `react-smooth` directly? Or are you wanting this change in recharts? I'm still not clear. If you are using `react-smooth` directly, installing 4.x shouldn't cause any breaking issues. Its just major version bumps of other packages

**Comment by denisx** [comment]
you need any help?

**Comment by ckifer** [comment]
@denisx released in 4.0.2
https://github.com/recharts/react-smooth/releases/tag/v4.0.2

**Comment by ckifer** [comment]
and actually scratch that about the 3.0 to 4.0 thing
https://github.com/recharts/recharts/blob/master/package.json#L73

recharts uses 4.0 in the master (2.x) branch so all good

**Comment by ckifer** [comment]
Let me know how much this actually helps your code splitting

**Comment by ckifer** [comment]
The caret (^) takes care of that. If you update your dependencies it should automatically install the latest patch version of react-smooth

**Comment by denisx** [comment]
if both packages at one project...

**Comment by ckifer** [comment]
react-smooth is installed implicitly because it is a dependency of recharts. Just run npm update

**Comment by denisx** [comment]
i think this is a bit mistake at package.json / files. no `index` at lib and es6 folders

**Comment by ckifer** [comment]
good catch. I started migrating to TS and looks like the build process isn't quite right
I'll patch again to prevent chaos from happening when people go to install later...

**Comment by ckifer** [comment]
4.03 published

**Comment by ckifer** [comment]
@denisx let me know as soon as you can try it :/ apologies for the miss there

**Pull request merged**
